# Generated by Django 2.2.6 on 2019-10-28 01:07

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0111_auto_20191027_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/app'), upload_to='products', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
