# Generated by Django 2.2.6 on 2019-10-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0112_auto_20191027_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='is_digital',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_shipping_required',
            field=models.BooleanField(default=False),
        ),
    ]
