# Generated by Django 2.2.6 on 2020-01-09 02:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0113_auto_20191028_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity_allocated',
            field=models.IntegerField(default=Decimal('1'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
