# Generated by Django 2.2.6 on 2020-01-10 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0114_auto_20200108_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='track_inventory',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight',
        ),
    ]
