# Generated by Django 2.2.6 on 2020-01-10 01:14

from django.db import migrations, models
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0115_auto_20200109_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Mass', null=True),
        ),
    ]
