# Generated by Django 2.2.6 on 2020-02-22 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0116_auto_20200109_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='products', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
