version: '2'

services:
  web:
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./saleor/:/app/saleor:Z
      - ./templates/:/app/templates:Z
      - ./tests/:/app/tests
      # prevents overshadowing of build-time assets
      - /app/saleor/static/assets
      - /app/templates/templated_email/compiled
      # shared volume between celery and web for media
      - saleor-media:/app/media
      - ./products:/app/products
      - ./locale:/app/locale
      - ./package.json:/app/package.json
      - ./webpack.config.js:/app/webpack.config.js

  db:
    ports:
      - 5432:5432

  celery:
    volumes:
      - ./saleor/:/app/saleor:Z
      - ./templates/:/app/templates:Z
      # prevents overshadowing of build-time assets
      - /app/templates/templated_email/compiled
      # shared volume between celery and web for media
      - saleor-media:/app/media

volumes:
  saleor-media:
