# Generated by Django 2.2.6 on 2020-01-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_raw_html_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
