# Generated by Django 2.2.6 on 2020-01-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20191018_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='product_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
